//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trade
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderproduct
    {
        public int OrderID { get; set; }
        public string ProductArticleNumber { get; set; }
        public int ProductAmount { get; set; }
    
        public virtual order order { get; set; }
        public virtual product product { get; set; }
    }
}
