//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trade
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.orderproduct = new HashSet<orderproduct>();
        }
    
        public string ProductArticleNumber { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public int ProductCategory { get; set; }
        public string ProductPhoto { get; set; }
        public int ProductManufacturer { get; set; }
        public int ProductSupplier { get; set; }
        public decimal ProductCost { get; set; }
        public Nullable<sbyte> ProductDiscountAmount { get; set; }
        public int ProductQuantityInStock { get; set; }
        public Nullable<sbyte> ProductMaxDiscount { get; set; }
        public int ProductUnit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderproduct> orderproduct { get; set; }
        public virtual productcategory productcategory1 { get; set; }
        public virtual productmanufacturer productmanufacturer1 { get; set; }
        public virtual productsupplier productsupplier1 { get; set; }
        public virtual unittype unittype { get; set; }
    }
}
