//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trade
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TradeEntities : DbContext
    {
        public TradeEntities()
            : base("name=TradeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<orderproduct> orderproduct { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<productcategory> productcategory { get; set; }
        public virtual DbSet<productmanufacturer> productmanufacturer { get; set; }
        public virtual DbSet<productsupplier> productsupplier { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<unittype> unittype { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
